name: models
description: a model package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  formz: ^0.4.1
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.2
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
